function draw3curve(S0,S1,SM,flg)
  % compute points on clothoid

  NPT = 100 ;
  cm = [1.000000000000000   0.598431372549020   0.200000000000000];

  XY = pointsOnClothoid( SM, 0:SM.L/NPT:SM.L ) ;
  if flg
    plot( XY(1,:), XY(2,:), '--', 'LineWidth', 2, 'Color', cm  ) ;
  else
    plot( XY(1,:), XY(2,:), '-r', 'LineWidth', 2 ) ;
  end
  hold on
  
  XY = pointsOnClothoid( S0, 0:S0.L/NPT:S0.L ) ;
  plot( XY(1,:), XY(2,:), '-b', 'LineWidth', 2 ) ;

  XY = pointsOnClothoid( S1, 0:S1.L/NPT:S1.L ) ;
  plot( XY(1,:), XY(2,:), '-k', 'LineWidth', 2 )  ;

  if false
  plot( SM.x, SM.y, '-mo',...
        'LineWidth', 1,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','m',...
        'MarkerSize',5 ) ;

  plot( S0.x, S0.y, '-mo',...
        'LineWidth', 1,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','m',...
        'MarkerSize',5 ) ;

  plot( S1.x, S1.y, '-mo',...
        'LineWidth', 1,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','m',...
        'MarkerSize',5 ) ;

  plot( XY(1,end), XY(2,end), '-mo',...
        'LineWidth', 1,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','r',...
        'MarkerSize',5 ) ;
  end
  title('Trajectory')
  grid on ;
  axis equal

end
