clc;
clear all;

NAMES = { ...
  'CircleArcMexWrapper', ...
} ;

LIBS = [ ...
  '-I../src ' ...
  '../src/G2lib.cc ' ...
  '../src/Line.cc ' ...
  '../src/Circle.cc ' ...
  '../src/Biarc.cc ' ...
  '../src/ClothoidG1.cc ' ...
  '../src/ClothoidG2.cc ' ...
  '../src/CubicRootsFlocke.cc ' ...
  '../src/Fresnel.cc ' ...
  '../src/Triangle2D.cc ' ...
] ;

disp('---------------------------------------------------------');
for k=1:length(NAMES)
  N=NAMES{k} ;
  fprintf(1,'Compiling: %s\n',N) ;

  CMD = [ 'while mislocked(''' N ''') ; munlock(''' N ''') ; end;'] ;
  disp(CMD);

  CMD = ['mex -output ',N,' -largeArrayDims ../src_mex/mex_',N,'.cc ', LIBS] ;
  if isunix
    if ismac
      CMD = [CMD, ' -lstdc++ CXXFLAGS="\$CXXFLAGS -Wall -O2 -g0"'] ;
    else
      CMD = [CMD, ' -lstdc++ CXXFLAGS="\$CXXFLAGS -Wall -O2 -g0"'] ;
    end
  elseif ispc
  end
  disp(CMD);
  eval(CMD);
end
disp('----------------------- DONE ----------------------------');
