function ode_eqns_V = ode_f(t,Y,J1,J2,K_D,K_S)
%ODE_F
%    ode_eqns_V = ODE_F(T,Y,J1,J2,K_D,K_S)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Apr-2025 23:34:57

t2 = Y(2);
t3 = Y(3);
t4 = Y(5);
ode_eqns_V = [t2;-(sin(t).*(-1.0./1.0e+1)+K_D.*t2+K_S.*t4)./J1;(K_S.*t4)./J2;t3;t2-t3];
end
